name: PROD Deployment workflow

on:
  push:
    branches: [ main ]

jobs:
  deployment-prod:
    name: PROD Deployment
    runs-on: ubuntu-latest
    environment: prod
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Decode base64 Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'keystore.jks'
          fileDir: './app/'
          encodedString: ${{ secrets.KEYSTORE }}

      - name: Declare VersionCode variable
        shell: bash
        run: |
          echo "appVersionCode=${{github.run_number}}" >> "$GITHUB_ENV"

      - name: Bump version
        uses: chkfung/android-version-actions@v1.2.1
        with:
          gradlePath: app/build.gradle.kts
          versionCode: ${{ env.appVersionCode }}

      - name: Build Release bundle
        env:
          KEY_STORE_PATH: ${{ secrets.KEY_STORE_PATH }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
        run: ./gradlew assembleProdRelease bundleProdRelease

      - name: Upload to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: Build Artifacts
          path: app/build/outputs/